### PR TITLE
Fix coin replacement

### PR DESCRIPTION
**Pull request by HarpyWar**
Switch only "BIP" <-> "MNT" coins and don't touch others that include these symbols

### CODE REVIEW

**Comment by lxgn** [comment]
There are both types of coins MNT and BIP in the test network and mainnet. Therefore, they change places. If you make the change in only one direction - there will be duplicates - which cause problems.

**Comment by lxgn** [comment]
Double quotes are not needed.

**Comment by HarpyWar** [comment]
> 
> 
> There are both types of coins MNT and BIP in the test network and mainnet. Therefore, they change places. If you make the change in only one direction - there will be duplicates - which cause problems.

It does not break this behavior. Only fix wrong replacement for other coins like BIPNET -> MNTNET

**Comment by lxgn** [comment]
merged

**Pull request merged**
